---
# pgAdmin
# Documentation: https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
# Purpose: Database web client for connecting to Postgres databases

- name: Create pgadmin Directory
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "{{ docker_data_pgadmin }}"

- name: Load the pgadmin env file
  become: true
  template:
    src: pgadmin.conf.env
    dest: "{{ docker_data_pgadmin }}/pgadmin.env"
    owner: root
    group: root

- name: Run 'pgadmin' - Docker Container
  docker_container:
    name: pgadmin
    image: dpage/pgadmin4:latest
    restart_policy: unless-stopped
    pull: true
    networks:
      - name: docker_ipvlan
        ipv4_address: "{{ pgadmin_container_ip }}"
    env_file: "{{ docker_data_pgadmin }}/pgadmin.env"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80",
        ]
      interval: 15s
      timeout: 10s
      retries: 5
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.http.routers.pgadmin.entrypoints: "websecure,web"
      traefik.http.routers.pgadmin.tls: "true"
      traefik.http.routers.pgadmin.rule: "Host(`pgadmin.{{ domain_name }}`)"
      traefik.http.routers.pgadmin.service: "pgadmin"
      traefik.http.services.pgadmin.loadBalancer.server.port: "80"
      traefik.http.routers.pgadmin.tls.certresolver: "letsencrypt"
