---
- name: Setup custom DNS - public
  template:
    src: 02-local-dns.conf
    dest: "{{ docker_data_pihole }}/etc-dnsmasq.d/02-local-dns.conf"
    mode: "0777"
  register: updated_dns_conf

- name: Restart PiHole for DNS entries (when changed)
  when: updated_dns_conf.changed
  docker_container:
    name: pihole
    state: started
    restart: true
