---
# Transmission
# Documentation: https://transmissionbt.com
# Purpose: To download Linux ISOs such as Debian & Mint

- name: Ensure 'torrent data' is created
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  with_items:
    - "/mnt/nas/torrent-data"

# Ensure that permissions are properly setup in NAS to mount directories
# 1. Login to Synology
# 2. Open Control Panel
# 3. Click Share(s) individually (i.e. Media)
# 4. Right click and hit Edit
# 5. Go to the NFS permissions Tab
# 6. Add hostname of the server

- name: Mount 'Transmission-Data'
  become: true
  mount:
    src: "{{ nas_ip }}:/volume1/Files/Torrent-Data"
    path: /mnt/nas/torrent-data
    state: mounted
    opts: rw,nolock,soft
    fstype: nfs

- name: Create docker data volume
  become: true
  file:
    path: /mnt/nas/torrent-data 
    state: directory
    mode: "0777"
    owner: root
    recurse: yes

- name: Run 'transmission-openvpn' - Docker Container
  docker_container:
    name: transmission-openvpn
    image: haugene/transmission-openvpn
    restart_policy: unless-stopped
    networks:
      - name: curidge
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/mnt/nas/torrent-data:/data"
      - "/etc/timezone:/etc/timezone:ro"
    env:
      OPENVPN_PROVIDER: "{{ vpn_provider }}"
      OPENVPN_CONFIG: "{{ vpn_country }}"
      OPENVPN_USERNAME: "{{ vpn_username }}"
      OPENVPN_PASSWORD: "{{ vpn_password }}"
      GLOBAL_APPLY_PERMISSIONS: "true"
      CREATE_TUN_DEVICE: "true"
      PUID: "1000"
      PGID: "1000"
      HEALTH_CHECK_HOST: "google.com"
      SELFHEAL: "false"
      LOCAL_NETWORK: "192.168.0.0/16"
    capabilities:
      - NET_ADMIN
    ports:
      - 9091:9091
    labels:
      com.centurylinklabs.watchtower.enable: "true"
