---
- hosts: application
  vars_files:
    - "applications.vars.yml"
    - "common.vars.yml"
    - "domain.vars.yml"
  roles:
    - role: common
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ user_name }}"
          oh_my_zsh:
            theme: bureau
            plugins:
              - git
              - debian
              - zsh-syntax-highlighting
              - zsh-autosuggestions
    - role: docker
    - role: applications
      tag:
        - applications
