---
- hosts: application
  vars_files:
    - "applications.vars.yml"
    - "common.vars.yml"
    - "domain.vars.yml"
  roles:
    - role: common
    - role: mashimom.oh-my-zsh
      ohmyzsh_theme: "lambda"
    - role: docker
    - role: applications
      tag:
        - applications
