---
- hosts: dns
  vars_files:
    - "common.vars.yml"
    - "domain.vars.yml"
    - "pihole.vars.yml"
  roles:
    - role: docker
      tag:
        - docker
    - role: dns
      tag:
        - dns-server