---
- hosts: media 
  vars_files:
    - "media.vars.yml"
    - "common.vars.yml"
    - "docker.vars.yml"
    - "domain.vars.yml"
  roles:
    - role: common
    - role: docker
    - role: media
      tag:
        - media